name: Build and run integration tests

on:
  push:
    branches: [ "staging" ]

jobs:
  build_unit_tests:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the rerpository
      uses: actions/checkout@v4
    - name: Setup .NET version 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Execute Integration Tests
      run: dotnet test HouseRentingSystem.Tests/HouseRentingSystem.Tests.csproj --no-build --verbosity normal
